import { OptimizeOptions } from 'svgo';
export default {
  plugins: [
    { name: 'cleanupAttrs' },
    { name: 'removeDoctype' },
    { name: 'removeXMLProcInst' },
    { name: 'removeComments' },
    { name: 'removeMetadata' },
    { name: 'removeTitle' },
    { name: 'removeDesc' },
    { name: 'removeUselessDefs' },
    { name: 'removeEditorsNSData' },
    { name: 'removeEmptyAttrs' },
    { name: 'removeHiddenElems' },
    { name: 'removeEmptyText' },
    { name: 'removeEmptyContainers' },
    { name: 'cleanupEnableBackground' },
    { name: 'convertStyleToAttrs' },
    { name: 'convertColors' },
    { name: 'convertPathData' },
    { name: 'removeUnknownsAndDefaults' },
    { name: 'removeNonInheritableGroupAttrs' },
    { name: 'removeUselessStrokeAndFill' },
    { name: 'removeUnusedNS' },
    { name: 'cleanupIDs' },
    { name: 'cleanupNumericValues' },
    { name: 'moveElemsAttrsToGroup' },
    { name: 'moveGroupAttrsToElems' },
    { name: 'collapseGroups' },
    { name: 'mergePaths' },
    { name: 'convertShapeToPath' },
    { name: 'sortAttrs' },
    { name: 'removeDimensions' },
    { name: 'removeAttrs' },
  ],
} as OptimizeOptions;
