name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn lerna bootstrap
    - run: yarn run build:icons
    - run: yarn run build:components
    - run: yarn run coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        name: codecov-umbrella
        flags: unittests
        directory: coverage
        verbose: true
      env:
        CI: true
