name: Quality

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/setup

      - run: pnpm run build:icons
      - run: pnpm run build:components

      - name: Run tests
        run: pnpm test

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/setup

      - name: Run ESLint
        run: pnpm lint

  types:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/setup

      - run: pnpm run build:icons
      - run: pnpm run build:components

      - name: Run typecheck
        run: pnpm typecheck

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/setup

      - run: pnpm run build:icons
      - run: pnpm run build:components

      - name: Run coverage
        run: pnpm run coverage

      - name: Upload @ohu-mobile/core coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          name: codecov-umbrella
          flags: unittests
          files: ./packages/ohu-mobile/coverage/coverage-final.json
          verbose: true
        env:
          CI: true

      - name: Upload @ohu/cli coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          name: codecov-umbrella
          flags: unittests
          files: ./packages/ohu-cli/coverage/coverage-final.json
          verbose: true
        env:
          CI: true
